const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={view:"people",search:"",type:"all",tier:"all",decade:"all",industry:"all",status:"all",venture:"all",sort:"name"};
let payload,rows=[],people=[],organizations=[],founders=[],funding=new Map();
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const clean=v=>v&&v!=="Unknown"?String(v):"";
const uniq=a=>[...new Set(a.filter(Boolean))];
const decade=y=>y&&/^\d{4}$/.test(String(y))?`${Math.floor(+y/10)*10}s`:"Unknown";
const safeUrl=value=>{try{const u=new URL(value);return["http:","https:"].includes(u.protocol)?u.href:""}catch{return""}};
const urls=value=>value&&value!=="Unknown"?uniq(String(value).split(";").map(v=>safeUrl(v.trim()))):[];
const money=n=>{n=+n||0;if(!n)return"undisclosed";if(n>=1e9)return`$${(n/1e9).toFixed(2).replace(/0$/,'')}B`;if(n>=1e6)return`$${(n/1e6).toFixed(n%1e6?1:0)}M`;return`$${Math.round(n/1e3)}K`};
const statusClass=value=>String(value||"").toLowerCase().replace(/[^a-z]+/g,"-");
const ext=(url,label)=>safeUrl(url)?`<a class="external-link" href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:"";
const sourceLinks=entries=>{const list=[];entries.forEach(([value,label])=>urls(value).forEach(url=>{if(!list.some(x=>x[0]===url))list.push([url,label])}));return list.length?`<div class="source-links">${list.map(([url,label])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`).join("")}</div>`:""};
const tags=(items,n=4)=>items.filter(Boolean).slice(0,n).map(v=>`<span class="tag">${esc(v)}</span>`).join("")+(items.length>n?`<span class="tag">+${items.length-n}</span>`:"");

function buildFounders(){
  const map=new Map();
  rows.forEach(r=>{
    if(!map.has(r.founder_name))map.set(r.founder_name,{id:r.founder_name,name:r.founder_name,year:clean(r.tjhsst_graduation_year),yearConfidence:r.tjhsst_year_confidence,tjEvidence:r.tjhsst_evidence,tjSource:r.tjhsst_source_url,university:clean(r.universities_attended),method:r.discovery_method,via:r.discovered_via,discoverySource:r.discovery_source_url,linkedin:clean(r.founder_linkedin),website:clean(r.founder_personal_website),rows:[]});
    map.get(r.founder_name).rows.push(r);
  });
  founders=[...map.values()].map(x=>({...x,decade:decade(x.year),industries:uniq(x.rows.map(r=>r.industry)),statuses:uniq(x.rows.map(r=>r.company_status)),ventures:uniq(x.rows.map(r=>r.venture_backed)),companies:uniq(x.rows.map(r=>r.company_name)),confidence:Math.min(...x.rows.map(r=>+r.confidence_score))}));
}

function options(select,values,label){select.innerHTML=`<option value="all">${label}</option>${values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("")}`}
function sortOptions(){
  const lists={people:[["name","name"],["year","class year"],["company","company"],["type","profile type"]],organizations:[["name","name"],["people","most people"],["founders","most verified founders"],["funding","disclosed funding"]],founders:[["year","class year"],["name","name"],["companies","most companies"],["confidence","highest confidence"]],records:[["year","class year"],["founder","founder name"],["company","company name"],["confidence","highest confidence"]]};
  const list=lists[state.view];if(!list.some(([v])=>v===state.sort))state.sort=list[0][0];
  $("#sort-filter").innerHTML=list.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");$("#sort-filter").value=state.sort;
}
function hydrate(){
  options($("#type-filter"),uniq(people.map(x=>x.profile_type)).sort(),"all people");
  options($("#tier-filter"),uniq(people.map(x=>x.research_status)).sort(),"all evidence levels");
  options($("#decade-filter"),uniq([...people.map(x=>decade(x.tjhsst_graduation_year)),...founders.map(x=>x.decade)]).sort((a,b)=>a==="Unknown"?1:b==="Unknown"?-1:a.localeCompare(b)),"all cohorts");
  options($("#industry-filter"),uniq([...people.map(x=>x.industry),...rows.map(x=>x.industry),...organizations.map(x=>x.industry)]).filter(x=>x!=="Unknown").sort(),"all industries");
  options($("#status-filter"),uniq([...rows.map(x=>x.company_status),...organizations.map(x=>x.status)]).filter(x=>x!=="Unknown").sort(),"all statuses");
  options($("#venture-filter"),uniq(rows.map(x=>x.venture_backed)).sort(),"all models");sortOptions();
}

function configureFilters(){
  const peopleView=state.view==="people";
  $("#type-filter").closest("label").hidden=!peopleView;
  $("#tier-filter").closest("label").hidden=!(peopleView||state.view==="organizations");
  $("#status-filter").closest("label").hidden=peopleView;
  $("#venture-filter").closest("label").hidden=!(state.view==="founders"||state.view==="records");
  const copy={people:["2×","Two evidence layers: research-grade founder records and a broader professional directory. Every profile names its layer."],organizations:[String(organizations.length),"Organizations are deduplicated across verified founder research and the supplied professional directory."],founders:["3–5","Only founder records meeting the original evidence threshold appear in this view."],records:["↗","Each relationship opens to the school evidence, founder evidence, company facts, and discovery provenance."]}[state.view];
  $("#confidence-note").innerHTML=`<b>${copy[0]}</b><p>${copy[1]}</p>`;
}

function searchMatch(item){if(!state.search)return true;const q=state.search.toLowerCase();return Object.values(item).flatMap(v=>Array.isArray(v)?v:[v]).join(" ").toLowerCase().includes(q)}
function filtered(){
  const source=state.view==="people"?people:state.view==="organizations"?organizations:state.view==="founders"?founders:rows;
  const list=source.filter(x=>{
    if(!searchMatch(x))return false;
    if(state.view==="people")return(state.type==="all"||x.profile_type===state.type)&&(state.tier==="all"||x.research_status===state.tier)&&(state.decade==="all"||decade(x.tjhsst_graduation_year)===state.decade)&&(state.industry==="all"||x.industry===state.industry);
    if(state.view==="organizations")return(state.tier==="all"||x.relationship_status===state.tier)&&(state.industry==="all"||x.industry===state.industry)&&(state.status==="all"||x.status===state.status);
    if(state.view==="founders")return(state.decade==="all"||x.decade===state.decade)&&(state.industry==="all"||x.industries.includes(state.industry))&&(state.status==="all"||x.statuses.includes(state.status))&&(state.venture==="all"||x.ventures.includes(state.venture));
    return(state.decade==="all"||decade(clean(x.tjhsst_graduation_year))===state.decade)&&(state.industry==="all"||x.industry===state.industry)&&(state.status==="all"||x.company_status===state.status)&&(state.venture==="all"||x.venture_backed===state.venture);
  });
  return list.sort((a,b)=>{
    if(state.view==="people"){if(state.sort==="year")return(+a.tjhsst_graduation_year||9999)-(+b.tjhsst_graduation_year||9999)||a.person_name.localeCompare(b.person_name);if(state.sort==="company")return a.company_name.localeCompare(b.company_name)||a.person_name.localeCompare(b.person_name);if(state.sort==="type")return a.profile_type.localeCompare(b.profile_type)||a.person_name.localeCompare(b.person_name);return a.person_name.localeCompare(b.person_name)}
    if(state.view==="organizations"){if(state.sort==="people")return b.people.length-a.people.length||a.name.localeCompare(b.name);if(state.sort==="founders")return b.verified_founders.length-a.verified_founders.length||a.name.localeCompare(b.name);if(state.sort==="funding")return(funding.get(b.name)||0)-(funding.get(a.name)||0)||a.name.localeCompare(b.name);return a.name.localeCompare(b.name)}
    if(state.view==="founders"){if(state.sort==="name")return a.name.localeCompare(b.name);if(state.sort==="companies")return b.companies.length-a.companies.length||a.name.localeCompare(b.name);if(state.sort==="confidence")return b.confidence-a.confidence||a.name.localeCompare(b.name);return(+a.year||9999)-(+b.year||9999)||a.name.localeCompare(b.name)}
    if(state.sort==="founder")return a.founder_name.localeCompare(b.founder_name)||a.company_name.localeCompare(b.company_name);if(state.sort==="company")return a.company_name.localeCompare(b.company_name)||a.founder_name.localeCompare(b.founder_name);if(state.sort==="confidence")return+b.confidence_score-+a.confidence_score||a.founder_name.localeCompare(b.founder_name);return(+a.tjhsst_graduation_year||9999)-(+b.tjhsst_graduation_year||9999)||a.founder_name.localeCompare(b.founder_name);
  });
}

function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]).join("").toUpperCase()}
function tierBadge(tier){const label=tier==="Research-grade verified"?"verified research":tier==="Partial-name lead"?"partial-name lead":"professional profile";return`<span class="tier-badge" data-tier="${statusClass(tier)}">${label}</span>`}
function personCard(x){const year=clean(x.tjhsst_graduation_year);return`<button class="result-card person-card" data-kind="person" data-id="${esc(x.person_name)}"><span class="avatar" aria-hidden="true">${esc(initials(x.person_name))}</span><span><span class="card-overline">${esc(x.profile_type)}${year?` · TJ ${esc(year)}`:""}</span><h3 class="result-title">${esc(x.person_name)}</h3><p class="result-description">${esc(x.current_title)}${clean(x.company_name)?` · ${esc(x.company_name)}`:""}</p><span class="tag-row">${tierBadge(x.research_status)}${clean(x.industry)?`<span class="tag">${esc(x.industry)}</span>`:""}</span></span><span class="result-meta"><strong>${esc(clean(x.person_location)||clean(x.company_headquarters)||"location unknown")}</strong><span>${esc(clean(x.undergrad_school_and_major)||"education not listed")}</span></span></button>`}
function organizationCard(x){const count=uniq([...x.people,...x.verified_founders]).length;const disclosed=funding.get(x.name)||0;return`<button class="result-card" data-kind="organization" data-id="${esc(x.name)}"><span class="result-index">${esc(clean(x.status)||"status unknown")}</span><span><span class="card-overline">${esc(clean(x.industry)||"industry unknown")}</span><h3 class="result-title">${esc(x.name)}</h3><p class="result-description">${esc(clean(x.description)||clean(x.subindustry)||clean(x.headquarters)||"Directory organization")}</p><span class="tag-row">${tierBadge(x.relationship_status)}${clean(x.company_size)?`<span class="tag">${esc(x.company_size)}</span>`:""}</span></span><span class="result-meta"><strong>${count} ${count===1?"person":"people"}</strong><span>${disclosed?`${money(disclosed)} captured`:esc(clean(x.headquarters)||"HQ unknown")}</span></span></button>`}
function founderCard(x){return`<button class="result-card" data-kind="founder" data-id="${esc(x.id)}"><span class="result-index">${esc(x.year||"year unknown")}</span><span><span class="card-overline">research-grade founder</span><h3 class="result-title">${esc(x.name)}</h3><p class="result-description">${esc(x.companies.join(" · "))}</p><span class="tag-row">${tags(x.industries)}</span></span><span class="result-meta"><strong>${x.companies.length} ${x.companies.length===1?"company":"companies"}</strong><span>confidence ${x.confidence}/5</span></span></button>`}
function recordCard(x){return`<button class="result-card" data-kind="record" data-id="${esc(x._id)}"><span class="result-index">${esc(clean(x.tjhsst_graduation_year)||"year unknown")}</span><span><span class="card-overline">verified founder relationship</span><h3 class="result-title">${esc(x.founder_name)} <span class="record-arrow">→</span> ${esc(x.company_name)}</h3><p class="result-description">${esc(x.founder_role)} · ${esc(x.company_description)}</p><span class="tag-row"><span class="status-pill" data-status="${esc(x.company_status)}">${esc(x.company_status)}</span><span class="tag">${esc(x.industry)}</span></span></span><span class="result-meta"><strong>${esc(x.total_funding)}</strong><span>confidence ${esc(x.confidence_score)}/5</span></span></button>`}
function render(){const list=filtered(),labels={people:"person",organizations:"organization",founders:"founder",records:"record"},noun=labels[state.view],plural=noun.endsWith("y")?noun.slice(0,-1)+"ies":noun+"s";$("#result-count").textContent=`${list.length} ${list.length===1?noun:plural}`;$("#results").innerHTML=list.map(x=>state.view==="people"?personCard(x):state.view==="organizations"?organizationCard(x):state.view==="founders"?founderCard(x):recordCard(x)).join("");$("#results").hidden=!list.length;$("#results").setAttribute("aria-busy","false");$("#empty-state").hidden=!!list.length;$$('[data-kind]').forEach(b=>b.onclick=()=>openDetail(b.dataset.kind,b.dataset.id));syncUrl()}

function fact(label,value){return`<div class="dialog-fact"><span>${esc(label)}</span><strong>${esc(clean(value)||"Unknown")}</strong></div>`}
function relationshipCard(r){return`<article class="relationship-card"><div class="relationship-card-head"><div><h4>${esc(r.company_name)}</h4><p>${esc(r.founder_role)} · ${esc(r.company_status)}</p></div><span class="tag">confidence ${esc(r.confidence_score)}/5</span></div><p>${esc(r.company_description)}</p>${sourceLinks([[r.tjhsst_source_url,"TJHSST evidence"],[r.founder_source_url,"founder evidence"],[r.additional_sources,"additional source"],[r.company_website,"company"]])}</article>`}
function personDetail(x){const verified=rows.filter(r=>r.founder_name===x.person_name);return`<p class="dialog-kicker">${esc(x.profile_type)} · ${esc(x.research_status)}</p><h2 class="dialog-title">${esc(x.person_name)}</h2><p class="dialog-subtitle">${esc(x.current_title)}${clean(x.company_name)?` · ${esc(x.company_name)}`:""}</p><div class="tag-row">${tierBadge(x.research_status)}${clean(x.industry)?`<span class="tag">${esc(x.industry)}</span>`:""}${clean(x.tjhsst_graduation_year)?`<span class="tag">TJ ${esc(x.tjhsst_graduation_year)}</span>`:""}</div><p class="dialog-links">${ext(x.founder_linkedin,"LinkedIn")}${ext(x.company_website,"company website")}${ext(x.company_linkedin,"company LinkedIn")}</p><section class="dialog-section"><h3>professional profile</h3><div class="dialog-facts">${fact("profile type",x.profile_type)}${fact("current title",x.current_title)}${fact("organization",x.company_name)}${fact("industry",x.industry)}${fact("company size",x.company_size)}${fact("company headquarters",x.company_headquarters)}${fact("location",x.person_location)}${fact("role started",x.year_started_current_role)}${fact("TJHSST class year",x.tjhsst_graduation_year)}${fact("undergraduate education",x.undergrad_school_and_major)}${fact("graduate education",x.grad_degree)}${fact("prior employers",x.notable_prior_employers)}</div></section><section class="dialog-section"><h3>directory notes</h3><div class="evidence-card"><p>${esc(x.notes)}</p><p class="microcopy">Collected ${esc(x.date_collected||"date unknown")} · ${esc(x.source_query)} · source row ${esc(x.source_row||"existing verified research")}</p></div></section>${verified.length?`<section class="dialog-section"><h3>${verified.length} research-grade founder ${verified.length===1?"relationship":"relationships"}</h3><div class="relationship-list">${verified.map(r=>relationshipCard(r)).join("")}</div></section>`:`<section class="dialog-section"><h3>evidence layer</h3><div class="evidence-card"><p>This profile is visible in the broader professional directory. It is not presented as a fully verified founder–company relationship unless a research-grade record appears above.</p></div></section>`}`}
function organizationDetail(x){const names=uniq([...x.verified_founders,...x.people]);return`<p class="dialog-kicker">organization · ${esc(x.relationship_status)}</p><h2 class="dialog-title">${esc(x.name)}</h2><p class="dialog-subtitle">${esc(clean(x.description)||clean(x.subindustry)||"Organization in the TJ professional network")}</p><div class="tag-row">${tierBadge(x.relationship_status)}${clean(x.industry)?`<span class="tag">${esc(x.industry)}</span>`:""}${clean(x.status)?`<span class="status-pill" data-status="${esc(x.status)}">${esc(x.status)}</span>`:""}</div><p class="dialog-links">${ext(x.website,"website")}${ext(x.linkedin,"LinkedIn")}</p><section class="dialog-section"><h3>organization facts</h3><div class="dialog-facts">${fact("industry",x.industry)}${fact("subindustry",x.subindustry)}${fact("headquarters",x.headquarters)}${fact("company size",x.company_size)}${fact("status",x.status)}${fact("captured funding",x.funding)}${fact("accelerator",x.accelerator)}${fact("evidence layer",x.relationship_status)}</div></section><section class="dialog-section"><h3>${names.length} connected ${names.length===1?"person":"people"}</h3><div class="name-grid">${names.map(name=>`<button data-person-jump="${esc(name)}"><span>${esc(initials(name))}</span>${esc(name)}${x.verified_founders.includes(name)?`<i>verified founder</i>`:""}</button>`).join("")}</div></section>`}
function founderDetail(x){return`<p class="dialog-kicker">founder record · confidence ${x.confidence}/5</p><h2 class="dialog-title">${esc(x.name)}</h2><p class="dialog-subtitle">${x.year?`TJHSST class of ${esc(x.year)}`:"TJHSST graduation year unknown"}${x.university?` · ${esc(x.university)}`:""}</p><div class="tag-row">${tags(x.industries,8)}</div><p class="dialog-links">${ext(x.linkedin,"LinkedIn")}${ext(x.website,"personal site")}</p><section class="dialog-section"><h3>school verification</h3><div class="evidence-card"><p>${esc(x.tjEvidence)}</p>${sourceLinks([[x.tjSource,"TJHSST evidence"]])}</div></section><section class="dialog-section"><h3>${x.companies.length} founded ${x.companies.length===1?"organization":"organizations"}</h3><div class="relationship-list">${x.rows.map(r=>relationshipCard(r)).join("")}</div></section><section class="dialog-section"><h3>discovery provenance</h3><div class="evidence-card"><h4>${esc(x.via)}</h4><p>${esc(x.method)}</p>${sourceLinks([[x.discoverySource,"discovery source"]])}</div></section>`}
function recordDetail(x){const facts=[["TJHSST year",clean(x.tjhsst_graduation_year)||"Unknown"],["year confidence",x.tjhsst_year_confidence],["founder role",x.founder_role],["founded",x.founding_year],["company status",x.company_status],["industry",`${x.industry} · ${x.subindustry}`],["headquarters",x.headquarters],["financing",x.venture_backed],["total funding",x.total_funding],["latest round",x.latest_known_round],["accelerator",x.accelerator],["notable investors",x.notable_investors],["exit",x.acquisition_or_exit],["acquirer",x.acquirer],["current founder role",x.current_founder_role],["university",x.universities_attended]];return`<p class="dialog-kicker">founder–company record · confidence ${esc(x.confidence_score)}/5</p><h2 class="dialog-title">${esc(x.founder_name)} <span class="record-arrow">→</span> ${esc(x.company_name)}</h2><p class="dialog-subtitle">${esc(x.company_description)}</p><section class="dialog-section"><h3>complete record</h3><div class="dialog-facts">${facts.map(([label,value])=>fact(label,value)).join("")}</div></section><section class="dialog-section"><h3>TJHSST evidence</h3><div class="evidence-card"><p>${esc(x.tjhsst_evidence)}</p>${sourceLinks([[x.tjhsst_source_url,"school source"]])}</div></section><section class="dialog-section"><h3>founder evidence</h3><div class="evidence-card"><p>${esc(x.founder_evidence)}</p>${sourceLinks([[x.founder_source_url,"founder source"],[x.additional_sources,"additional source"],[x.company_website,"company website"]])}</div></section>`}
function openDetail(kind,id){const x=kind==="person"?people.find(v=>v.person_name===id):kind==="organization"?organizations.find(v=>v.name===id):kind==="founder"?founders.find(v=>v.id===id):rows.find(v=>v._id===id);if(!x)return;$("#detail-content").innerHTML=kind==="person"?personDetail(x):kind==="organization"?organizationDetail(x):kind==="founder"?founderDetail(x):recordDetail(x);$("#detail-dialog").showModal();$$('[data-person-jump]',$("#detail-content")).forEach(button=>button.onclick=()=>openDetail("person",button.dataset.personJump))}

function setView(view){state.view=view;state.sort=view==="people"||view==="organizations"?"name":"year";$$('[data-view]').forEach(b=>{const on=b.dataset.view===view;b.classList.toggle("active",on);b.setAttribute("aria-selected",on)});configureFilters();sortOptions();render()}
function reset(){Object.assign(state,{search:"",type:"all",tier:"all",decade:"all",industry:"all",status:"all",venture:"all",sort:state.view==="people"||state.view==="organizations"?"name":"year"});$("#search-input").value="";["type","tier","decade","industry","status","venture"].forEach(k=>$("#"+k+"-filter").value="all");sortOptions();render()}
function syncUrl(){const p=new URLSearchParams;if(state.view!=="people")p.set("view",state.view);if(state.search)p.set("q",state.search);for(const [key,param] of [["type","type"],["tier","tier"],["decade","cohort"],["industry","industry"],["status","status"]])if(state[key]!=="all")p.set(param,state[key]);history.replaceState(null,"",`${location.pathname}${p.size?`?${p}`:""}${location.hash}`)}
function restore(){const p=new URLSearchParams(location.search);if(["people","organizations","founders","records"].includes(p.get("view")))state.view=p.get("view");state.search=p.get("q")||"";for(const [key,param] of [["type","type"],["tier","tier"],["decade","cohort"],["industry","industry"],["status","status"]])state[key]=p.get(param)||"all"}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$("#search-input").oninput=e=>{state.search=e.target.value.trim();render()};["type","tier","decade","industry","status","venture","sort"].forEach(key=>$("#"+key+"-filter").onchange=e=>{state[key]=e.target.value;render()});$("#clear-filters").onclick=reset;$$('[data-reset]').forEach(b=>b.onclick=reset);$("#dialog-close").onclick=()=>$("#detail-dialog").close();$("#detail-dialog").onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};document.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search-input").focus()}if(e.key==="/"&&document.activeElement.tagName!=="INPUT"){e.preventDefault();$("#search-input").focus()}}}

async function init(){try{const res=await fetch("/tj/data.json");if(!res.ok)throw Error("data");payload=await res.json();rows=payload.verified_founders.map((r,i)=>({...r,_id:String(i)}));people=payload.people_directory;organizations=payload.organizations_directory;funding=new Map(payload.analysis.largest_publicly_disclosed_company_totals.map(x=>[x.company,x.amount_usd]));buildFounders();restore();hydrate();configureFilters();$("#people-stat").textContent=payload.directory_summary.unique_people;$("#founder-stat").textContent=payload.analysis.unique_founders;$("#company-stat").textContent=payload.directory_summary.unique_organizations;$("#relationship-stat").textContent=payload.analysis.founder_company_records;$("#source-stat").textContent=payload.sources.length;$("#profile-stat").textContent=payload.directory_summary.professional_profiles;$("#lead-stat").textContent=payload.directory_summary.partial_name_leads;$("#network-stat").textContent=payload.analysis.founders_discovered_through_recursive_network_expansion;const d=new Date(`${payload.metadata.research_date}T12:00:00`);$("#research-date").textContent=`researched through ${d.toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}).toLowerCase()}`;bind();$("#search-input").value=state.search;["type","tier","decade","industry","status"].forEach(k=>$("#"+k+"-filter").value=state[k]);$$('[data-view]').forEach(b=>{const on=b.dataset.view===state.view;b.classList.toggle("active",on);b.setAttribute("aria-selected",on)});sortOptions();render()}catch(e){console.error(e);$("#load-error").hidden=false;$("#result-count").textContent="database unavailable";$("#results").setAttribute("aria-busy","false")}}
init();
