const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={view:"founders",search:"",decade:"all",industry:"all",status:"all",venture:"all",sort:"year"};
let payload,rows=[],founders=[],companies=[],funding=new Map();
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const clean=v=>v&&v!=="Unknown"?String(v):"";
const uniq=a=>[...new Set(a.filter(Boolean))];
const decade=y=>y&&/^\d{4}$/.test(String(y))?`${Math.floor(+y/10)*10}s`:"Unknown";
const safeUrl=value=>{try{const u=new URL(value);return ["http:","https:"].includes(u.protocol)?u.href:""}catch{return""}};
const urls=value=>value&&value!=="Unknown"?uniq(String(value).split(";").map(v=>safeUrl(v.trim()))):[];
const money=n=>{n=+n||0;if(!n)return"undisclosed";if(n>=1e9)return`$${(n/1e9).toFixed(2).replace(/0$/,"")}B`;if(n>=1e6)return`$${(n/1e6).toFixed(n%1e6?1:0)}M`;return`$${Math.round(n/1e3)}K`};

function build(){
  const fm=new Map(),cm=new Map();
  rows.forEach(r=>{
    if(!fm.has(r.founder_name))fm.set(r.founder_name,{id:r.founder_name,name:r.founder_name,year:clean(r.tjhsst_graduation_year),yearConfidence:r.tjhsst_year_confidence,tjEvidence:r.tjhsst_evidence,tjSource:r.tjhsst_source_url,university:clean(r.universities_attended),method:r.discovery_method,via:r.discovered_via,discoverySource:r.discovery_source_url,linkedin:clean(r.founder_linkedin),website:clean(r.founder_personal_website),rows:[]});
    fm.get(r.founder_name).rows.push(r);
    if(!cm.has(r.company_name))cm.set(r.company_name,{id:r.company_name,name:r.company_name,website:clean(r.company_website),founded:clean(r.founding_year),status:r.company_status,industry:r.industry,subindustry:r.subindustry,description:r.company_description,hq:clean(r.headquarters),venture:r.venture_backed,totalFunding:r.total_funding,round:r.latest_known_round,investors:r.notable_investors,accelerator:r.accelerator,exit:r.acquisition_or_exit,funding:funding.get(r.company_name)||0,rows:[]});
    cm.get(r.company_name).rows.push(r);
  });
  founders=[...fm.values()].map(x=>({...x,decade:decade(x.year),industries:uniq(x.rows.map(r=>r.industry)),statuses:uniq(x.rows.map(r=>r.company_status)),ventures:uniq(x.rows.map(r=>r.venture_backed)),companies:uniq(x.rows.map(r=>r.company_name)),confidence:Math.min(...x.rows.map(r=>+r.confidence_score))}));
  companies=[...cm.values()].map(x=>({...x,founders:uniq(x.rows.map(r=>r.founder_name)),decades:uniq(x.rows.map(r=>decade(clean(r.tjhsst_graduation_year)))),confidence:Math.min(...x.rows.map(r=>+r.confidence_score))}));
}

function options(select,values,label){select.innerHTML=`<option value="all">${label}</option>${values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("")}`}
function sortOptions(){const list=state.view==="founders"?[["year","class year"],["name","name"],["companies","most companies"],["confidence","highest confidence"]]:state.view==="companies"?[["name","name"],["founded","founding year"],["funding","disclosed funding"],["founders","most TJ founders"]]:[["year","class year"],["founder","founder name"],["company","company name"],["confidence","highest confidence"]];if(!list.some(([v])=>v===state.sort))state.sort=list[0][0];$("#sort-filter").innerHTML=list.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");$("#sort-filter").value=state.sort}
function hydrate(){
  options($("#decade-filter"),uniq(founders.map(x=>x.decade)).sort((a,b)=>a==="Unknown"?1:b==="Unknown"?-1:a.localeCompare(b)),"all cohorts");
  options($("#industry-filter"),uniq(rows.map(r=>r.industry)).sort(),"all industries");
  options($("#status-filter"),uniq(rows.map(r=>r.company_status)).sort(),"all statuses");
  options($("#venture-filter"),uniq(rows.map(r=>r.venture_backed)).sort(),"all models");sortOptions();
}

function searchMatch(x){if(!state.search)return true;const q=state.search.toLowerCase();const text=state.view==="founders"?[x.name,x.year,x.university,x.method,...x.companies,...x.industries]:state.view==="companies"?[x.name,x.description,x.industry,x.subindustry,x.hq,x.accelerator,x.investors,...x.founders]:Object.values(x);return text.join(" ").toLowerCase().includes(q)}
function filtered(){
  const list=(state.view==="founders"?founders:state.view==="companies"?companies:rows).filter(x=>{
    if(!searchMatch(x))return false;
    if(state.view==="founders")return(state.decade==="all"||x.decade===state.decade)&&(state.industry==="all"||x.industries.includes(state.industry))&&(state.status==="all"||x.statuses.includes(state.status))&&(state.venture==="all"||x.ventures.includes(state.venture));
    if(state.view==="companies")return(state.decade==="all"||x.decades.includes(state.decade))&&(state.industry==="all"||x.industry===state.industry)&&(state.status==="all"||x.status===state.status)&&(state.venture==="all"||x.venture===state.venture);
    return(state.decade==="all"||decade(clean(x.tjhsst_graduation_year))===state.decade)&&(state.industry==="all"||x.industry===state.industry)&&(state.status==="all"||x.company_status===state.status)&&(state.venture==="all"||x.venture_backed===state.venture);
  });
  return list.sort((a,b)=>{if(state.view==="founders"){if(state.sort==="name")return a.name.localeCompare(b.name);if(state.sort==="companies")return b.companies.length-a.companies.length||a.name.localeCompare(b.name);if(state.sort==="confidence")return b.confidence-a.confidence||a.name.localeCompare(b.name);return(+a.year||9999)-(+b.year||9999)||a.name.localeCompare(b.name)}if(state.view==="companies"){if(state.sort==="founded")return(+a.founded||9999)-(+b.founded||9999)||a.name.localeCompare(b.name);if(state.sort==="funding")return b.funding-a.funding||a.name.localeCompare(b.name);if(state.sort==="founders")return b.founders.length-a.founders.length||a.name.localeCompare(b.name);return a.name.localeCompare(b.name)}if(state.sort==="founder")return a.founder_name.localeCompare(b.founder_name)||a.company_name.localeCompare(b.company_name);if(state.sort==="company")return a.company_name.localeCompare(b.company_name)||a.founder_name.localeCompare(b.founder_name);if(state.sort==="confidence")return+b.confidence_score-+a.confidence_score||a.founder_name.localeCompare(b.founder_name);return(+a.tjhsst_graduation_year||9999)-(+b.tjhsst_graduation_year||9999)||a.founder_name.localeCompare(b.founder_name)});
}
const tags=(a,n=3)=>a.slice(0,n).map(v=>`<span class="tag">${esc(v)}</span>`).join("")+(a.length>n?`<span class="tag">+${a.length-n}</span>`:"");
function founderCard(x){return`<button class="result-card" data-kind="founder" data-id="${esc(x.id)}"><span class="result-index">${esc(x.year||"year unknown")}</span><span><h3 class="result-title">${esc(x.name)}</h3><p class="result-description">${esc(x.companies.join(" · "))}</p><span class="tag-row">${tags(x.industries)}</span></span><span class="result-meta"><strong>${x.companies.length} ${x.companies.length===1?"company":"companies"}</strong><span>confidence ${x.confidence}/5</span></span></button>`}
function companyCard(x){const f=x.funding?money(x.funding):clean(x.totalFunding)||"funding unknown";return`<button class="result-card" data-kind="company" data-id="${esc(x.id)}"><span class="result-index">${esc(x.founded||"year unknown")}</span><span><h3 class="result-title">${esc(x.name)}</h3><p class="result-description">${esc(x.description)}</p><span class="tag-row"><span class="status-pill" data-status="${esc(x.status)}">${esc(x.status)}</span><span class="tag">${esc(x.industry)}</span>${x.accelerator!=="Unknown"&&x.accelerator!=="None"?`<span class="tag">${esc(x.accelerator)}</span>`:""}</span></span><span class="result-meta"><strong>${esc(f)}</strong><span>${x.founders.length} TJ ${x.founders.length===1?"founder":"founders"}</span></span></button>`}
function recordCard(x){return`<button class="result-card" data-kind="record" data-id="${esc(x._id)}"><span class="result-index">${esc(clean(x.tjhsst_graduation_year)||"year unknown")}</span><span><h3 class="result-title">${esc(x.founder_name)} <span class="record-arrow">→</span> ${esc(x.company_name)}</h3><p class="result-description">${esc(x.founder_role)} · ${esc(x.company_description)}</p><span class="tag-row"><span class="status-pill" data-status="${esc(x.company_status)}">${esc(x.company_status)}</span><span class="tag">${esc(x.industry)}</span><span class="tag">${esc(x.venture_backed)}</span></span></span><span class="result-meta"><strong>${esc(x.total_funding)}</strong><span>confidence ${esc(x.confidence_score)}/5</span></span></button>`}
function render(){const list=filtered(),noun=state.view==="founders"?"founder":state.view==="companies"?"company":"record";$("#result-count").textContent=`${list.length} ${list.length===1?noun:noun+"s"}`;$("#results").innerHTML=list.map(x=>state.view==="founders"?founderCard(x):state.view==="companies"?companyCard(x):recordCard(x)).join("");$("#results").hidden=!list.length;$("#results").setAttribute("aria-busy","false");$("#empty-state").hidden=!!list.length;$$('[data-kind]').forEach(b=>b.onclick=()=>openDetail(b.dataset.kind,b.dataset.id));syncUrl()}

const ext=(url,label)=>safeUrl(url)?`<a class="external-link" href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:"";
function sources(entries){const list=[];entries.forEach(([value,label])=>urls(value).forEach(url=>{if(!list.some(x=>x[0]===url))list.push([url,label])}));return list.length?`<div class="source-links">${list.map(([url,label])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`).join("")}</div>`:""}
function founderDetail(x){return`<p class="dialog-kicker">founder record · confidence ${x.confidence}/5</p><h2 class="dialog-title">${esc(x.name)}</h2><p class="dialog-subtitle">${x.year?`TJHSST class of ${esc(x.year)}`:"TJHSST graduation year unknown"}${x.university?` · ${esc(x.university)}`:""}</p><div class="tag-row">${tags(x.industries,8)}</div>${x.linkedin||x.website?`<p>${ext(x.linkedin,"LinkedIn")} ${ext(x.website,"personal site")}</p>`:""}<section class="dialog-section"><h3>school verification</h3><div class="evidence-card"><p>${esc(x.tjEvidence)}</p>${sources([[x.tjSource,"TJHSST evidence"]])}</div></section><section class="dialog-section"><h3>${x.companies.length} founded ${x.companies.length===1?"organization":"organizations"}</h3><div class="relationship-list">${x.rows.map(r=>`<article class="relationship-card"><div class="relationship-card-head"><div><h4>${esc(r.company_name)}</h4><p>${esc(r.founder_role)} · ${esc(r.company_status)}</p></div><span class="status-pill" data-status="${esc(r.company_status)}">${esc(r.industry)}</span></div><p>${esc(r.company_description)}</p><div class="dialog-facts"><div class="dialog-fact"><span>funding</span><strong>${esc(r.total_funding)}</strong></div><div class="dialog-fact"><span>exit / status</span><strong>${esc(r.acquisition_or_exit)}</strong></div></div><p>${esc(r.founder_evidence)}</p>${sources([[r.company_website,"company"],[r.founder_source_url,"founder evidence"],[r.additional_sources,"additional source"]])}</article>`).join("")}</div></section><section class="dialog-section"><h3>discovery provenance</h3><div class="evidence-card"><h4>${esc(x.via)}</h4><p>${esc(x.method)}</p>${sources([[x.discoverySource,"discovery source"]])}</div></section>`}
function companyDetail(x){return`<p class="dialog-kicker">company record · confidence ${x.confidence}/5</p><h2 class="dialog-title">${esc(x.name)}</h2><p class="dialog-subtitle">${esc(x.description)}</p><div class="tag-row"><span class="status-pill" data-status="${esc(x.status)}">${esc(x.status)}</span><span class="tag">${esc(x.industry)}</span><span class="tag">${esc(x.subindustry)}</span></div>${x.website?`<p>${ext(x.website,"company website")}</p>`:""}<section class="dialog-section"><h3>company facts</h3><div class="dialog-facts"><div class="dialog-fact"><span>founded</span><strong>${esc(x.founded||"Unknown")}</strong></div><div class="dialog-fact"><span>headquarters</span><strong>${esc(x.hq||"Unknown")}</strong></div><div class="dialog-fact"><span>financing model</span><strong>${esc(x.venture)}</strong></div><div class="dialog-fact"><span>funding</span><strong>${esc(x.totalFunding)}</strong></div><div class="dialog-fact"><span>latest round</span><strong>${esc(x.round)}</strong></div><div class="dialog-fact"><span>status / exit</span><strong>${esc(x.exit)}</strong></div></div></section><section class="dialog-section"><h3>${x.founders.length} verified TJ ${x.founders.length===1?"founder":"founders"}</h3><div class="relationship-list">${x.rows.map(r=>`<article class="relationship-card"><div class="relationship-card-head"><div><h4>${esc(r.founder_name)}</h4><p>${esc(r.founder_role)}${r.tjhsst_graduation_year?` · TJ '${esc(String(r.tjhsst_graduation_year).slice(-2))}`:""}</p></div><span class="tag">confidence ${esc(r.confidence_score)}/5</span></div><p>${esc(r.founder_evidence)}</p>${sources([[r.tjhsst_source_url,"TJHSST evidence"],[r.founder_source_url,"founder evidence"],[r.additional_sources,"additional source"]])}</article>`).join("")}</div></section>${x.accelerator!=="Unknown"||x.investors!=="Unknown"?`<section class="dialog-section"><h3>ecosystem</h3><div class="dialog-facts"><div class="dialog-fact"><span>accelerator</span><strong>${esc(x.accelerator)}</strong></div><div class="dialog-fact"><span>notable investors</span><strong>${esc(x.investors)}</strong></div></div></section>`:""}`}
function recordDetail(x){const facts=[["TJHSST year",clean(x.tjhsst_graduation_year)||"Unknown"],["year confidence",x.tjhsst_year_confidence],["founder role",x.founder_role],["founded",x.founding_year],["company status",x.company_status],["industry",`${x.industry} · ${x.subindustry}`],["headquarters",x.headquarters],["financing",x.venture_backed],["total funding",x.total_funding],["latest round",x.latest_known_round],["accelerator",x.accelerator],["notable investors",x.notable_investors],["exit",x.acquisition_or_exit],["acquirer",x.acquirer],["current founder role",x.current_founder_role],["university",x.universities_attended]];return`<p class="dialog-kicker">founder–company record · confidence ${esc(x.confidence_score)}/5</p><h2 class="dialog-title">${esc(x.founder_name)} <span class="record-arrow">→</span> ${esc(x.company_name)}</h2><p class="dialog-subtitle">${esc(x.company_description)}</p><div class="tag-row"><span class="status-pill" data-status="${esc(x.company_status)}">${esc(x.company_status)}</span><span class="tag">${esc(x.industry)}</span><span class="tag">${esc(x.venture_backed)}</span></div><section class="dialog-section"><h3>complete record</h3><div class="dialog-facts">${facts.map(([label,value])=>`<div class="dialog-fact"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`).join("")}</div></section><section class="dialog-section"><h3>TJHSST evidence</h3><div class="evidence-card"><p>${esc(x.tjhsst_evidence)}</p>${sources([[x.tjhsst_source_url,"school source"]])}</div></section><section class="dialog-section"><h3>founder evidence</h3><div class="evidence-card"><p>${esc(x.founder_evidence)}</p>${sources([[x.founder_source_url,"founder source"],[x.additional_sources,"additional source"],[x.company_website,"company website"]])}</div></section><section class="dialog-section"><h3>discovery provenance</h3><div class="evidence-card"><h4>${esc(x.discovered_via)}</h4><p>${esc(x.discovery_method)}</p>${sources([[x.discovery_source_url,"discovery source"]])}</div></section>`}
function openDetail(kind,id){const x=kind==="founder"?founders.find(v=>v.id===id):kind==="company"?companies.find(v=>v.id===id):rows.find(v=>v._id===id);if(!x)return;$("#detail-content").innerHTML=kind==="founder"?founderDetail(x):kind==="company"?companyDetail(x):recordDetail(x);$("#detail-dialog").showModal()}

function setView(view){state.view=view;state.sort=view==="companies"?"name":"year";$$('[data-view]').forEach(b=>{const on=b.dataset.view===view;b.classList.toggle("active",on);b.setAttribute("aria-selected",on)});sortOptions();render()}
function reset(){Object.assign(state,{search:"",decade:"all",industry:"all",status:"all",venture:"all",sort:state.view==="companies"?"name":"year"});$("#search-input").value="";["decade","industry","status","venture"].forEach(k=>$(`#${k}-filter`).value="all");sortOptions();render()}
function syncUrl(){const p=new URLSearchParams;if(state.view!=="founders")p.set("view",state.view);if(state.search)p.set("q",state.search);if(state.decade!=="all")p.set("cohort",state.decade);if(state.industry!=="all")p.set("industry",state.industry);if(state.status!=="all")p.set("status",state.status);history.replaceState(null,"",`${location.pathname}${p.size?`?${p}`:""}${location.hash}`)}
function restore(){const p=new URLSearchParams(location.search);if(["founders","companies","records"].includes(p.get("view")))state.view=p.get("view");state.search=p.get("q")||"";state.decade=p.get("cohort")||"all";state.industry=p.get("industry")||"all";state.status=p.get("status")||"all"}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$("#search-input").oninput=e=>{state.search=e.target.value.trim();render()};[["decade","decade"],["industry","industry"],["status","status"],["venture","venture"],["sort","sort"]].forEach(([id,key])=>$(`#${id}-filter`).onchange=e=>{state[key]=e.target.value;render()});$("#clear-filters").onclick=reset;$$('[data-reset]').forEach(b=>b.onclick=reset);$("#dialog-close").onclick=()=>$("#detail-dialog").close();$("#detail-dialog").onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};document.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search-input").focus()}if(e.key==="/"&&document.activeElement.tagName!=="INPUT"){e.preventDefault();$("#search-input").focus()}}}

async function init(){try{const res=await fetch("/tj/data.json");if(!res.ok)throw Error("data");payload=await res.json();rows=payload.verified_founders.map((r,i)=>({...r,_id:String(i)}));funding=new Map(payload.analysis.largest_publicly_disclosed_company_totals.map(x=>[x.company,x.amount_usd]));restore();build();hydrate();$("#founder-stat").textContent=payload.analysis.unique_founders;$("#company-stat").textContent=payload.analysis.unique_companies;$("#relationship-stat").textContent=payload.analysis.founder_company_records;$("#funding-stat").textContent=money(payload.analysis.total_publicly_disclosed_funding_usd);$("#source-stat").textContent=payload.sources.length;$("#lead-stat").textContent=payload.unverified_leads.length;$("#rejected-stat").textContent=payload.rejected_candidates.length;$("#network-stat").textContent=payload.analysis.founders_discovered_through_recursive_network_expansion;const d=new Date(`${payload.metadata.research_date}T12:00:00`);$("#research-date").textContent=`researched through ${d.toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}).toLowerCase()}`;bind();$("#search-input").value=state.search;["decade","industry","status"].forEach(k=>$(`#${k}-filter`).value=state[k]);$$('[data-view]').forEach(b=>{const on=b.dataset.view===state.view;b.classList.toggle("active",on);b.setAttribute("aria-selected",on)});sortOptions();render()}catch(e){console.error(e);$("#load-error").hidden=false;$("#result-count").textContent="database unavailable";$("#results").setAttribute("aria-busy","false")}}
init();
